---
- name: first ansible playbook
  hosts: ansibleclients
  become: yes

  tasks:
  - name: "create a file in remote hosts"
    file:
      path: /root/mynotfile
      state: touch

  - name: "sleep for 2"
    shell: sleep 2
  
  - name: "copy a file to remote hosts from ansible server"
    copy:
      src: /root/myfile.txt
      dest: /root/myfile.txt