---
- name: test
  hosts: test
  become: yes

  tasks:
  - name: test connection
    ping:

  - name: create user
    user:
      name: testc
    notify:
      - test2

  handlers:
  - name: test2
    ping:
