---
- name: loop ansible playbook
  hosts: ansibleclients
  become: yes

  tasks:
  - name: install packages
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - httpd
      - tree
      - source-highlight
      - bind-utils