---
- name: Homework
  hosts: test
  become: yes
 
  tasks:
    - name: Create user "ansible-test"
      user:
        name: ansible-test
        state: present
 
    - name: Stop service httpd
      service:
        name: httpd
        state: stopped
 
    - name: Install nginx
      yum:
        name: nginx
        state: latest
